[project]
name = "joe-lending"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=3.0.1",
    "web3>=7.14.1",
]

[tool.ruff.lint]                                                                                                                                                                                                                                                                               
select = ["I"]

[dependency-groups]
dev = [
    "ruff>=0.15.7",
]
